Pull request try
supermax500/labor_exchange pull request #1
Opened 2024-12-17 07:41 UTC by supermax500

2024-12-17 07:46 UTC, Rognak commented on src/web/routers/__init__.py
> +from .job import router as job_router
pick: необходимо установить pre-commit

Прочитай инструкцию и прогони свои коммиты в данном PR
https://pre-commit.com/

2024-12-17 07:47 UTC, Rognak commented on src/web/routers/job.py
> +    async with db.Session() as session:
issue: запросы всегда делаем на уровне repositories

https://pybit.es/articles/repository-pattern-in-python/

2024-12-17 07:49 UTC, Rognak commented on pyproject.toml
>  pathlib = "^1.0.1"
pick, thought, etc... 

https://conventionalcomments.org/

2024-12-17 07:50 UTC, Rognak commented on src/web/routers/job.py
> +        jobs = res.scalars().all()
thought: пока не реализован слой `repository` предлагаю запросы сделать по-умолчанию, возвоащающие условные hello-world

2024-12-17 07:51 UTC, Rognak commented on src/web/routers/response.py
> +    async with db.Session() as session:
pick: аналогично

2024-12-17 07:51 UTC, MaratLOTR commented on src/web/routers/job.py
> +        query = select(Job).limit(limit)
pick: Запрос не учитывает поле skip, которое передано в ендпоинт

Здесь необходимо реализовать пагинацию с помощью limit offset
https://postgrespro.ru/docs/postgresql/9.4/queries-limit

2024-12-17 07:52 UTC, Rognak requested changes
pick: давай начнем pull-request с уровня repository

2024-12-17 08:03 UTC, Rognak commented
https://www.cosmicpython.com/book/chapter_01_domain_model.html

2024-12-17 08:04 UTC, Rognak commented on src/web/schemas/job.py
> +from decimal import Decimal
https://www.conventionalcommits.org/en/v1.0.0/

2024-12-19 05:10 UTC, supermax500 commented on src/web/routers/__init__.py
> +from .job import router as job_router
done

2024-12-23 21:02 UTC, merged