feat: Add job repository
supermax500/labor_exchange pull request #2
Opened 2024-12-25 22:45 UTC by supermax500

Реализован JobRepository, добавлены unit-тесты

2024-12-28 06:51 UTC, MaratLOTR commented on src/repositories/job_repository.py
> +                #user=job_user,
pick: Добавить user

2024-12-28 06:51 UTC, MaratLOTR commented on src/repositories/job_repository.py
> +    async def update(self, id: int, job_update_dto: JobUpdateSchema) -> UserModel:
nonblocking-pick: id- внутреннее зарезервированное имя, поэтому его лучше не использовать. Можно сделать id_

2024-12-28 06:51 UTC, MaratLOTR commented on src/repositories/job_repository.py
> +    async def update(self, id: int, job_update_dto: JobUpdateSchema) -> UserModel:
Поменять метод для Job

2024-12-28 06:51 UTC, MaratLOTR commented on src/repositories/job_repository.py
> +                raise ValueError("Вакансия не найдена")
nonblocking-pick: В Цифровом-Керне мы игнорируем ситуацию, когда удаляется не существующий объект

2024-12-28 07:06 UTC, MaratLOTR commented on src/tests/test_jobs_repository.py
> +    assert len(all_jobs) == 1
nonblocking-pick: Предлагаю здесь проверять, что количество записей >1, чтобы была видна разница между retrieve и retirve-many

2024-12-28 07:08 UTC, MaratLOTR commented on src/tests/test_jobs_repository.py
> +async def test_update_bad_salary(job_repository, sa_session):
pick: Посмотреть тест, он не проверяет bad_salary

2024-12-28 07:08 UTC, MaratLOTR commented on src/tests/test_jobs_repository.py
> +    assert not res
pick: assert res is not None

2024-12-28 07:10 UTC, MaratLOTR commented on src/web/schemas/job.py
>      id: Optional[int] = None
nonblocking-pick: 
```
id: int | None = None
```

2024-12-28 07:12 UTC, MaratLOTR commented on src/tests/test_jobs_repository.py
> +async def test_update_bad_salary(job_repository, sa_session):
Возможно bad_salary не стоит проверять, т.к. это вызов проверка работу модели pydantic, который не относится к repository

2025-01-13 05:04 UTC, Rognak commented on src/.env.dev
> +#POSTGRES_USER="user1"
pick: необходимо удалить неиспользуемый код

2025-01-13 05:07 UTC, Rognak commented on src/repositories/job_repository.py
> +        return self.__to_job_model(job_from_db=job, include_relations=False)
thought: подумать в сторону создания универсального класса `SQLToModel` (как пример)

2025-01-13 05:14 UTC, Rognak commented on src/tests/test_jobs_repository.py
> +    try:
pick-blocking: есть специальный метод для этого

```python
with pytest.rises(<ExceptionType>):
    <код>
```

2025-01-13 05:15 UTC, Rognak commented on src/tests/test_jobs_repository.py
> +async def test_update_bad_salary(job_repository, sa_session):
issue

2025-01-13 05:17 UTC, Rognak commented on src/web/schemas/job.py
> +    def valid_salary_range(self) -> Self:
issue: DRY

https://docs.pydantic.dev/2.0/usage/validators/#reuse-validators

2025-01-13 05:18 UTC, Rognak requested changes
Исправить комментарии и залить

2025-01-15 09:24 UTC, supermax500 commented on src/web/schemas/job.py
>      id: Optional[int] = None
С одной стороны так правильнее, функциональненько, но с другой стороны нечитабельно немного, но думаю привыкнуть можно

2025-01-16 05:19 UTC, MaratLOTR commented on src/config/db_settings.py
> +            #port=5433,
pick: Неиспользуемый код

2025-01-16 05:19 UTC, MaratLOTR commented on src/tests/test_jobs_repository.py
>      all_jobs = await job_repository.retrieve_many()
pick: Необходимо добавлять несколько job в session, тогда получится проверять, что в БД лежит более 1 записи

2025-01-16 05:19 UTC, MaratLOTR commented on src/tests/test_jobs_repository.py
>      assert all_jobs
pick: Провеять, что all_jobs is not None and all_jobs != []

2025-01-20 05:11 UTC, merged